version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./nerf_studio.db
      - DEBUG=false
      - MAX_CONCURRENT_JOBS=2
      - UPLOAD_DIR=./uploads
      - MODEL_DIR=./models
    volumes:
      - backend_data:/app/data
      - backend_uploads:/app/uploads
      - backend_models:/app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
  backend_uploads:
  backend_models: